-- MySQL Script generated by MySQL Workbench
-- lun. 02 mars 2020 22:14:09 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_paris
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_paris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_paris` ;
USE `db_paris` ;

-- -----------------------------------------------------
-- Table `db_paris`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`categorie` (
  `nom` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ville`, `nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`prestation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`prestation` (
  `id_prestation` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  `categorie_ville` VARCHAR(45) NOT NULL,
  `categorie_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prestation`, `categorie_ville`, `categorie_nom`),
  INDEX `fk_prestation_categorie1_idx` (`categorie_ville` ASC, `categorie_nom` ASC) VISIBLE,
  CONSTRAINT `fk_prestation_categorie1`
    FOREIGN KEY (`categorie_ville` , `categorie_nom`)
    REFERENCES `db_paris`.`categorie` (`ville` , `nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`prestataire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`prestataire` (
  `id_prestataire` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `tel_mobile` VARCHAR(45) NULL DEFAULT NULL,
  `tel_fixe` VARCHAR(45) NULL DEFAULT NULL,
  `adresse_entreprise` VARCHAR(45) NULL DEFAULT NULL,
  `url_qrcode` VARCHAR(45) NULL DEFAULT NULL,
  `prix_heure` FLOAT NULL DEFAULT NULL,
  `supplement` VARCHAR(45) NULL DEFAULT NULL,
  `company_name` VARCHAR(45) NULL,
  `code_postal` INT NULL,
  `email` VARCHAR(60) NULL,
  `nb_heure_min` FLOAT NULL,
  `prix_recurrent` VARCHAR(45) NULL,
  `categorie_ville` VARCHAR(45) NOT NULL,
  `categorie_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prestataire`, `categorie_ville`, `categorie_nom`),
  INDEX `fk_prestataire_categorie1_idx` (`categorie_ville` ASC, `categorie_nom` ASC) VISIBLE,
  CONSTRAINT `fk_prestataire_categorie1`
    FOREIGN KEY (`categorie_ville` , `categorie_nom`)
    REFERENCES `db_paris`.`categorie` (`ville` , `nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `ville_reference` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `mdp` VARCHAR(256) NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `date_inscription` DATETIME NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `cp` INT NULL,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`, `ville_reference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`abonnement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`abonnement` (
  `id_abonnement` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `cout` FLOAT NULL DEFAULT NULL,
  `nb_heure` FLOAT NULL DEFAULT NULL,
  `temps` INT NULL,
  `heure_debut` INT NULL,
  `heure_fin` INT NULL,
  PRIMARY KEY (`id_abonnement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`reservation` (
  `id_reservation` INT NOT NULL AUTO_INCREMENT,
  `date_debut` DATETIME NULL,
  `date_fin` DATETIME NULL,
  `user_id_user` INT NOT NULL,
  `user_ville_reference` VARCHAR(45) NOT NULL,
  `prestation_id_prestation` INT NOT NULL,
  `prestation_ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_reservation`, `user_id_user`, `user_ville_reference`, `prestation_id_prestation`, `prestation_ville`),
  INDEX `fk_reservation_user1_idx` (`user_id_user` ASC, `user_ville_reference` ASC) VISIBLE,
  INDEX `fk_reservation_prestation1_idx` (`prestation_id_prestation` ASC, `prestation_ville` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id_user` , `user_ville_reference`)
    REFERENCES `db_paris`.`user` (`id_user` , `ville_reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_prestation1`
    FOREIGN KEY (`prestation_id_prestation`)
    REFERENCES `db_paris`.`prestation` (`id_prestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`facturation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`facturation` (
  `id_facturation` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `cout` FLOAT NULL DEFAULT NULL,
  `id_user` INT NOT NULL,
  `devis` INT NULL,
  `reservation_id_reservation` INT NOT NULL,
  `prestataire_id_prestataire` INT NOT NULL,
  `prestataire_ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_facturation`, `prestataire_id_prestataire`, `prestataire_ville`),
  INDEX `fk_facturation_client1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_facturation_reservation1_idx` (`reservation_id_reservation` ASC) VISIBLE,
  INDEX `fk_facturation_prestataire1_idx` (`prestataire_id_prestataire` ASC, `prestataire_ville` ASC) VISIBLE,
  CONSTRAINT `fk_facturation_client1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_paris`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturation_reservation1`
    FOREIGN KEY (`reservation_id_reservation`)
    REFERENCES `db_paris`.`reservation` (`id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturation_prestataire1`
    FOREIGN KEY (`prestataire_id_prestataire`)
    REFERENCES `db_paris`.`prestataire` (`id_prestataire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`contrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`contrat` (
  `id_contrat` INT NOT NULL AUTO_INCREMENT,
  `duree` INT NULL DEFAULT NULL,
  `path_contrat` VARCHAR(45) NULL DEFAULT NULL,
  `salaire` FLOAT NULL,
  `date_debut` DATETIME NULL,
  `date_fin` DATETIME NULL,
  `prestataire_id_prestataire` INT NOT NULL,
  `prestataire_ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contrat`, `prestataire_id_prestataire`, `prestataire_ville`),
  INDEX `fk_contrat_prestataire1_idx` (`prestataire_id_prestataire` ASC, `prestataire_ville` ASC) VISIBLE,
  CONSTRAINT `fk_contrat_prestataire1`
    FOREIGN KEY (`prestataire_id_prestataire`)
    REFERENCES `db_paris`.`prestataire` (`id_prestataire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`souscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`souscription` (
  `abonnement_id_abonnement` INT NOT NULL,
  `date` DATETIME NULL,
  `heure_restante` FLOAT NULL,
  `user_id_user` INT NOT NULL,
  `user_ville_reference` VARCHAR(45) NOT NULL,
  INDEX `fk_client_has_abonnement_abonnement1_idx` (`abonnement_id_abonnement` ASC) VISIBLE,
  PRIMARY KEY (`abonnement_id_abonnement`, `user_id_user`, `user_ville_reference`),
  INDEX `fk_souscription_user1_idx` (`user_id_user` ASC, `user_ville_reference` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_abonnement_abonnement1`
    FOREIGN KEY (`abonnement_id_abonnement`)
    REFERENCES `db_paris`.`abonnement` (`id_abonnement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_souscription_user1`
    FOREIGN KEY (`user_id_user` , `user_ville_reference`)
    REFERENCES `db_paris`.`user` (`id_user` , `ville_reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_paris`.`demande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_paris`.`demande` (
  `id_demande` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL,
  `date` DATETIME NULL,
  `etat` TINYINT NULL,
  `user_id_user` INT NOT NULL,
  `user_ville_reference` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_demande`, `user_id_user`, `user_ville_reference`),
  INDEX `fk_demande_user1_idx` (`user_id_user` ASC, `user_ville_reference` ASC) VISIBLE,
  CONSTRAINT `fk_demande_user1`
    FOREIGN KEY (`user_id_user` , `user_ville_reference`)
    REFERENCES `db_paris`.`user` (`id_user` , `ville_reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
